module.exports = {
  apps: [{
    name: "pickleball-courts",
    script: "node_modules/next/dist/bin/next",
    args: "start -p 3001",
    instances: 1,
    exec_mode: "fork",
    env: {
      NODE_ENV: "production",
      PORT: 3001,
      DATABASE_URL: "postgresql://thepalmcourt:Aqn1cNzzyTw4rUCYri3S5tY2G@localhost:5432/thepalmcourt",
      NEXTAUTH_URL: "https://thepalmcourt.ph",
      NEXTAUTH_SECRET: "SBq3y1Sq7oi7NaChH3zsLb6LSVTG7X1k5QeO6XuNvFk=",
      AUTH_SECRET: "SBq3y1Sq7oi7NaChH3zsLb6LSVTG7X1k5QeO6XuNvFk=",
      AUTH_TRUST_HOST: "true",
      UPLOADTHING_TOKEN: "eyJhcGlLZXkiOiJza19saXZlX2RlMzE3MDc2YWVhNGJkNmZlNjZjNzFjYjcwZmMyNWZhNTZmMzZhNTM5NDU4ODgwMDRhYjBjMDg1MjczZjRiNTQiLCJhcHBJZCI6Imh5cnd5OXhlYzkiLCJyZWdpb25zIjpbInNlYTEiXX0=",
    },
    env_production: {
      NODE_ENV: "production",
      PORT: 3001,
      DATABASE_URL: "postgresql://thepalmcourt:Aqn1cNzzyTw4rUCYri3S5tY2G@localhost:5432/thepalmcourt",
      NEXTAUTH_URL: "https://thepalmcourt.ph",
      NEXTAUTH_SECRET: "SBq3y1Sq7oi7NaChH3zsLb6LSVTG7X1k5QeO6XuNvFk=",
      AUTH_SECRET: "SBq3y1Sq7oi7NaChH3zsLb6LSVTG7X1k5QeO6XuNvFk=",
      AUTH_TRUST_HOST: "true",
      UPLOADTHING_TOKEN: "eyJhcGlLZXkiOiJza19saXZlX2RlMzE3MDc2YWVhNGJkNmZlNjZjNzFjYjcwZmMyNWZhNTZmMzZhNTM5NDU4ODgwMDRhYjBjMDg1MjczZjRiNTQiLCJhcHBJZCI6Imh5cnd5OXhlYzkiLCJyZWdpb25zIjpbInNlYTEiXX0=",
    },
    error_file: "./logs/err.log",
    out_file: "./logs/out.log",
    log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    merge_logs: true,
  }],
}
